"""Initial Migration

Revision ID: 7abed5381e07
Revises: 
Create Date: 2025-09-10 01:57:23.398530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abed5381e07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dioceses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dioceses_id'), 'dioceses', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('subscription_plan_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_plan_features_id'), 'subscription_plan_features', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('parishes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diocese_id', sa.UUID(), nullable=False),
    sa.Column('parish_data', sa.JSON(), nullable=True),
    sa.Column('member_number_prefix', sa.String(), nullable=False),
    sa.Column('member_number_suffix', sa.String(), nullable=False),
    sa.Column('parish_settings', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diocese_id'], ['dioceses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parishes_id'), 'parishes', ['id'], unique=False)
    op.create_table('subscription_plan_feature_pivot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_plan_id', sa.UUID(), nullable=True),
    sa.Column('feature_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('is_inherited', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['subscription_plan_features.id'], ),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plan_feature_pivot_id'), 'subscription_plan_feature_pivot', ['id'], unique=False)
    op.create_table('fund_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('account_suffix', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'inactive', name='fundprojectstatus'), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_fund_projects_id'), 'fund_projects', ['id'], unique=False)
    op.create_index(op.f('ix_fund_projects_parish_id'), 'fund_projects', ['parish_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('member_no', sa.String(), nullable=False),
    sa.Column('member_data', sa.JSON(), nullable=False),
    sa.Column('member_group', sa.Enum('men_in_action', 'youth', 'womens_guild', 'elderly', name='membergroup'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_index(op.f('ix_members_parish_id'), 'members', ['parish_id'], unique=False)
    op.create_table('parish_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('subscription_plan_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_renewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'expired', 'grace_period', 'cancelled', name='subscription_status', native_enum=False), nullable=False),
    sa.Column('next_subscription_plan_id', sa.UUID(), nullable=True),
    sa.Column('last_plan_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['next_subscription_plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parish_subscriptions_id'), 'parish_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_parish_subscriptions_parish_id'), 'parish_subscriptions', ['parish_id'], unique=False)
    op.create_table('sacraments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sacraments_id'), 'sacraments', ['id'], unique=False)
    op.create_index(op.f('ix_sacraments_parish_id'), 'sacraments', ['parish_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diocese_id', sa.UUID(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['diocese_id'], ['dioceses.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('event_title', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_description', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('marked_by', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.create_index(op.f('ix_attendances_parish_id'), 'attendances', ['parish_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('diocese_id', sa.UUID(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diocese_id'], ['dioceses.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('invited_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_invited_users_id'), 'invited_users', ['id'], unique=False)
    op.create_index(op.f('ix_invited_users_token'), 'invited_users', ['token'], unique=True)
    op.create_table('login_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_activity_id'), 'login_activity', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.Enum('reminder', 'info', name='notificationtype'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('parish_subscription_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parish_subscription_id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('current_plan_id', sa.UUID(), nullable=False),
    sa.Column('next_plan_id', sa.UUID(), nullable=False),
    sa.Column('change_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scheduled_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['current_plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['next_plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['parish_subscription_id'], ['parish_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parish_subscription_changes_id'), 'parish_subscription_changes', ['id'], unique=False)
    op.create_table('sacrament_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_no', sa.String(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('sacrament_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('generate_certificate', sa.Boolean(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('outstanding_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['sacrament_id'], ['sacraments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no')
    )
    op.create_index(op.f('ix_sacrament_records_id'), 'sacrament_records', ['id'], unique=False)
    op.create_index(op.f('ix_sacrament_records_sacrament_id'), 'sacrament_records', ['sacrament_id'], unique=False)
    op.create_table('subscription_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parish_subscription_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parish_subscription_id'], ['parish_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_payments_id'), 'subscription_payments', ['id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('permission_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('sacrament_record_id', sa.UUID(), nullable=False),
    sa.Column('certificate_for', sa.String(), nullable=False),
    sa.Column('certificate_no', sa.String(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['sacrament_record_id'], ['sacrament_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_index(op.f('ix_certificates_parish_id'), 'certificates', ['parish_id'], unique=False)
    op.create_index(op.f('ix_certificates_sacrament_record_id'), 'certificates', ['sacrament_record_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_type', sa.Enum('donation', 'offering', 'tithe', 'thanksgiving', 'sacrament', 'project', name='collectiontype'), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('sacrament_record_id', sa.UUID(), nullable=True),
    sa.Column('collection_method', sa.Enum('mpesa', 'cash', 'card', 'cheque', 'bank_transfer', name='collectionmethod'), nullable=False),
    sa.Column('collection_data', sa.JSON(), nullable=False),
    sa.Column('contributor_data', sa.JSON(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['fund_projects.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sacrament_record_id'], ['sacrament_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_collection_method'), 'collections', ['collection_method'], unique=False)
    op.create_index(op.f('ix_collections_collection_type'), 'collections', ['collection_type'], unique=False)
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    op.create_index(op.f('ix_collections_member_id'), 'collections', ['member_id'], unique=False)
    op.create_index(op.f('ix_collections_parish_id'), 'collections', ['parish_id'], unique=False)
    op.create_index(op.f('ix_collections_project_id'), 'collections', ['project_id'], unique=False)
    op.create_index(op.f('ix_collections_sacrament_record_id'), 'collections', ['sacrament_record_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parish_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('subscription_payment_id', sa.UUID(), nullable=True),
    sa.Column('receipt_no', sa.String(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parish_id'], ['parishes.id'], ),
    sa.ForeignKeyConstraint(['subscription_payment_id'], ['subscription_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_collection_id'), 'receipts', ['collection_id'], unique=False)
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_index(op.f('ix_receipts_parish_id'), 'receipts', ['parish_id'], unique=False)
    op.create_index(op.f('ix_receipts_subscription_payment_id'), 'receipts', ['subscription_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_subscription_payment_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_parish_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_collection_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_collections_sacrament_record_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_project_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_parish_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_member_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_collection_type'), table_name='collections')
    op.drop_index(op.f('ix_collections_collection_method'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_certificates_sacrament_record_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_parish_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_subscription_payments_id'), table_name='subscription_payments')
    op.drop_table('subscription_payments')
    op.drop_index(op.f('ix_sacrament_records_sacrament_id'), table_name='sacrament_records')
    op.drop_index(op.f('ix_sacrament_records_id'), table_name='sacrament_records')
    op.drop_table('sacrament_records')
    op.drop_index(op.f('ix_parish_subscription_changes_id'), table_name='parish_subscription_changes')
    op.drop_table('parish_subscription_changes')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_login_activity_id'), table_name='login_activity')
    op.drop_table('login_activity')
    op.drop_index(op.f('ix_invited_users_token'), table_name='invited_users')
    op.drop_index(op.f('ix_invited_users_id'), table_name='invited_users')
    op.drop_table('invited_users')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendances_parish_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sacraments_parish_id'), table_name='sacraments')
    op.drop_index(op.f('ix_sacraments_id'), table_name='sacraments')
    op.drop_table('sacraments')
    op.drop_index(op.f('ix_parish_subscriptions_parish_id'), table_name='parish_subscriptions')
    op.drop_index(op.f('ix_parish_subscriptions_id'), table_name='parish_subscriptions')
    op.drop_table('parish_subscriptions')
    op.drop_index(op.f('ix_members_parish_id'), table_name='members')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_fund_projects_parish_id'), table_name='fund_projects')
    op.drop_index(op.f('ix_fund_projects_id'), table_name='fund_projects')
    op.drop_table('fund_projects')
    op.drop_index(op.f('ix_subscription_plan_feature_pivot_id'), table_name='subscription_plan_feature_pivot')
    op.drop_table('subscription_plan_feature_pivot')
    op.drop_index(op.f('ix_parishes_id'), table_name='parishes')
    op.drop_table('parishes')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_subscription_plan_features_id'), table_name='subscription_plan_features')
    op.drop_table('subscription_plan_features')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_dioceses_id'), table_name='dioceses')
    op.drop_table('dioceses')
    # ### end Alembic commands ###
