import logging
import random
from datetime import date, timedelta
from fastapi import HTTPException
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session
from log_config import logger
from db.models.attendance import Attendance
from db.models.parish import Parish
from db.models.user import User


def check_attendance_records_exist(db: Session) -> bool:
    """
    Check if any attendance records already exist in the database.
    Returns True if at least one record exists, otherwise False.
    """
    return db.query(Attendance.id).first() is not None


def create_attendance_records(db: Session):
    """
    Seed 5 attendance records for each parish with random attendance data.
    Skips parishes with no users. Rolls back on DB errors and logs accordingly.
    """
    try:
        parishes = db.query(Parish).all()
        users = db.query(User.id).all()

        if not parishes:
            logger.warning("No parishes found. Attendance seeding skipped!")
            return

        if not users:
            logger.warning("No users available. Attendance seeding skipped!")
            return

        for parish in parishes:
            parish_users = db.query(User.id).filter(User.parish_id == parish.id).all()

            if not parish_users:
                logger.info("Skipped attendance creation for a parish with no users!")
                continue

            parish_name = parish.parish_data.get("parish_name")

            for i in range(1, 6):
                attendance = Attendance(
                    parish_id=parish.id,
                    event_title=f"Parish Event {i} - {parish_name}",
                    event_type=random.choice(
                        ["Mass", "Retreat", "Seminar", "Prayer Service"]
                    ),
                    event_description="Autogenerated parish event for attendance logging!",
                    event_date=date.today() - timedelta(days=random.randint(0, 30)),
                    marked_by=random.choice(parish_users).id,
                    data={
                        "visitors_present": random.randint(1, 10),
                        "children_present": random.randint(10, 50),
                        "men_present": random.randint(20, 60),
                        "women_present": random.randint(20, 70),
                        "remarks": random.choice(
                            [
                                "Well attended despite rain.",
                                "Fewer children than expected.",
                                "Visitors participated actively.",
                                "Women outnumbered men significantly.",
                                "Very interactive session.",
                            ]
                        ),
                    },
                    is_archived=False,
                )
                db.add(attendance)

            logger.info("Attendance records created for parish!")

        db.commit()
        logger.info("Attendance seeding completed!")

    except HTTPException as e:
        logger.warning(f"{e.status_code} | {e.detail}", exc_info=True)
        raise

    except SQLAlchemyError:
        db.rollback()
        logger.error(
            "500 | Database error during attendance record data seeding!",
            exc_info=True,
        )
        raise HTTPException(status_code=500, detail="A database error occurred!")
